const recommendations = [
  {
    date: "August 20, 2024",
    name: "Levon Budaghyan",
    position: "Prompt Engineer",
    relationship: "Levon worked with Lilan but on different teams",
    image: "assets/img/recommendation/Levon Budaghyan.png",
    linkedin: "https://www.linkedin.com/in/levonbudaghyan/",
    recommendation:
      "Lilan Dayananda is an exceptional person with outstanding social and communication skills. Lilian’s ability to connect with people and build strong relationships made him a key figure in maintaining communication. His clear, concise communication ensured that everyone felt heard and valued, making him an invaluable asset to any team.",
  },
  {
    date: "July 14, 2024",
    name: "Kinjal Dave",
    position: "Scientist",
    relationship: "Kinjal worked with Lilan on the same team",
    image: "assets/img/recommendation/Kinjal Dave.png",
    linkedin: "https://www.linkedin.com/in/kinjal-dave-380954108/",
    recommendation:
      "I have had the privilege of collaborating with Lilan at the UN COPUOS 2024, as an SGAC Delegate. His exceptional leadership skills and ability to inspire others were evident in every conversation we had. Lilan is a natural expert and his passion for uses of space for sustainable development of Earth is evident. His dedication towards the vision and mission that he wants to materialise as a business is excellent and inspiring.",
  },
  {
    date: "July 4, 2024",
    name: "Arpan Yagnik",
    position: "Associate Professor of Advertising",
    relationship: "Arpan worked with Lilan on the same team",
    image: "assets/img/recommendation/Arpan Yagnik.png",
    linkedin: "https://www.linkedin.com/in/arpan-yagnik-defeatfearbecreative/",
    recommendation:
      "Lilan has a heart of gold. I say so because his compassion extends much beyond him. He is a deeply caring and committed social entrepreneur. He has a proven track record of leadership where he has inspired innovation, delivered impactful results, and led an intergenerational team. \n\nLilan is a perpetual learner with a growth mindset. He is gentle in his demeanor and firm in his clarity. Through his work he has impacted hundreds of thousands of people on the planet. He has won many prestigious accolades, which are a testament of his committed efforts to provide food security. \n\nLilan is a beacon of hope shining bright in the bleak times. I wish him the best and offer my strongest recommendation for leading the efforts in restoring balance in this immensely imbalanced world.",
  },
  {
    date: "May 23, 2024",
    name: "Ron Lawler",
    position: "Consultant",
    relationship: "Ron worked with Lilan but on different teams",
    image: "assets/img/recommendation/Ron Lawler.png",
    linkedin: "https://www.linkedin.com/in/ron-lawler-2214ab43/",
    recommendation:
      "I had the privilege of meeting Lilan at an international Initiatives of Change forum in Caux , Switzerland last year entitled, “Healing the Wounds of the Past”. Then in December when I visited his country he gave me insight into the Sri Lankan cultural heritage. Midst the acute challenges that Sri Lanka has faced in the past few years he remains resolute in finding very practical ways forward. By nature this goes beyond Sri Lanka to our global challenges of climate change and related issues such as sustainability and food security. He is working at the “coal face” through ensuring cutting edge technologies are made available to those who need them in addressing these matters. \n\nHe has been recognised internationally for his social entrepreneurial success. This has a foundation in his own organisation, ELZIAN AGRO. However, he is tireless in his commitment beyond that space to sharing and learning so that humankind can make a better fist of meeting its current monumental needs. Lilan’s work is encouraging and hope giving, and it was a wonderful opportunity last year to share in that spirit in both Caux and Sri Lanka. His future contribution will enrich many important initiatives to heal and change our globe.",
  },
  {
    date: "May 17, 2024",
    name: "Mohan Bhagwandas",
    position: "Change Management",
    relationship: "Mohan worked with Lilan on the same team",
    image: "assets/img/recommendation/Mohan Bhagwandas.png",
    linkedin: "https://www.linkedin.com/in/mohan-bhagwandas-earthbanc-67333a/",
    recommendation:
      "Lilan is working on groundbreaking technologies that can make a major impact on the furture of our global community.",
  },
  {
    date: "April 10, 2024",
    name: "Sainsanaa Amarsanaa",
    position: "Permitting & Compliance Associate",
    relationship: "Sainsanaa worked with Lilan on the same team",
    image: "assets/img/recommendation/Sainsanaa Amarsanaa.png",
    linkedin: "https://www.linkedin.com/in/sainsanaa-amarsanaa-1ab300bb/",
    recommendation:
      "It was a pleasure connecting with Lilan during the YECAP-AGYLE Training Program 2023 in Thailand. Our interactions, alongside those of other young climate leaders, and lecture sessions from UNFCCC experts provided valuable insights into climate negotiation processes. One example that stands out is when we became on group to propose ideas to other groups in a short period his quick mind and ability to think from different perspectives was invaluable to help broaden the concepts. I believe he is a talented and motivated individual with the skills and experience to excel in contributing to the goals of the Paris Agreement.",
  },
  {
    date: "April 9, 2024",
    name: "Herbert Bangura",
    position: "Regional Speaker",
    relationship: "Herbert worked with Lilan but on different teams",
    image: "assets/img/recommendation/Herbert Bangura.png",
    linkedin: "https://www.linkedin.com/in/herbert-bangura-76b12420/",
    recommendation:
      "I met Lilan, the inspiring founder, at the FAO Global Conference on Sustainable Livestock Transformation in Rome, Italy. Lilan's innovative thinking and entrepreneurial spirit stood out to me, as he is passionate about incorporating technology to facilitate a sustainable transition towards climate-smart, data-driven precision agriculture. His expertise and enthusiasm for leveraging technology to create positive change in agriculture were evident. Lilan's leadership and creative problem-solving skills make him a significant influence in the agri-tech industry. I am impressed by his ability to identify issues in food systems and develop groundbreaking solutions. It was a pleasure to connect with such a diverse youth changemaker, who is dedicated to advancing agricultural technology. I have no reservations about his abilities and therefore very pleased to recommend him for this opportunity.",
  },
  {
    date: "March 29, 2024",
    name: "Kim-Hang Ho",
    position: "Data Analyst",
    relationship: "Kim-Hang worked with Lilan on the same team",
    image: "assets/img/recommendation/Kim-Hang Ho.png",
    linkedin: "https://www.linkedin.com/in/kimhangho/",
    recommendation:
      "I have worked with Lilan during the Unleash Hackathon. He is the great leader in the team. I was impressed by the way he thinks, the way he process to solve the problem. It was an amazing opportunity to work with Lilan.",
  },
  {
    date: "December 24, 2023",
    name: "Kalpit Prajapati",
    position: "Co-Founder & CEO at Apeiro Energy",
    relationship: "Kalpit worked with Lilan on the same team",
    image: "assets/img/recommendation/Kalpit Prajapati.png",
    linkedin: "https://www.linkedin.com/in/kalpit-prajapati-apeiro-energy/",
    recommendation:
      "I met Lilan at COP 28 Dubai and he was coming from Rwanda from attending an event and straight onto another. He is a very soft spoken guy with an excellent understanding of his domain, integrating advanced IoT with farming and developing farms of future. He understands Geo-politics quite well and I loved our conversations on micro-economic solutions to global challenges.",
  },
  {
    date: "November 24, 2023",
    name: "Kilino Stojkov",
    position: "General Manager",
    relationship: "Kilino worked with Lilan on the same team",
    image: "assets/img/recommendation/Kilino Stojkov.png",
    linkedin: "https://www.linkedin.com/in/kilino-stojkov-42975a125/",
    recommendation:
      "I had the pleasure of meeting Lilan during my time at the Youth4Climate: Powering Action flagship event in the high-level Week of the 77th Session of the United Nations General Assembly in New York City, United States of America (USA). During our interactions, I had the opportunity to witness the remarkable innovations spearheaded by Lilan's company in the realm of sustainable mechanization within agriculture through precision agriculture and technology.",
  },
  {
    date: "November 24, 2023",
    name: "Moe Soliman",
    position: "Development Alchemist",
    relationship: "Moe worked with Lilan on the same team",
    image: "assets/img/recommendation/Moe Soliman.png",
    linkedin: "https://www.linkedin.com/in/moesolim/",
    recommendation:
      "I had the good fortune to connect with the visionary founder Lilan. Throughout our interactions, I was thoroughly impressed by Lilan's innovative thinking and entrepreneurial mindset. His depth of knowledge and passion for leveraging technology to drive positive change in agriculture left a strong impression on me. Lilan's leadership abilities and creative solutions demonstrated that he is an influential force in the agtech industry. I remain inspired by his talent for identifying problems in food systems and developing game-changing solutions. It was truly motivating to interact with someone so committed to advancing agricultural technology.",
  },
  {
    date: "November 24, 2023",
    name: "Khalid Roumieh",
    position: "Entrepreneur",
    relationship: "Khalid worked with Lilan on the same team",
    image: "assets/img/recommendation/Khalid Roumieh.png",
    linkedin: "https://www.linkedin.com/in/khalidroumieh/",
    recommendation:
      "I had the pleasure of being in the same cohort as Lilan during the Founder Institute’s Food Accelerator Program, where he showcased exceptional qualities as an entrepreneur and a visionary founder. His drive and determination set a high standard for success in the agri-tech field. Throughout the years, Lilan has consistently spearheaded award-winning initiatives that push the boundaries of innovation in tackling food security and climate challenges. His expertise in leveraging IoT, AI, and Data Science has led to groundbreaking advancements in the industry. His commitment to eradicating hunger through sustainable solutions, driven by cutting-edge precision technology, is truly commendable.",
  },
  {
    date: "September 30, 2023",
    name: "Prima Yangzi Mishra",
    position: "Research Intern",
    relationship: "Prima worked with Lilan on the same team",
    image: "assets/img/recommendation/Prima Yangzi Mishra.png",
    linkedin: "https://www.linkedin.com/in/primayangzimishra/",
    recommendation:
      "Lilan and I were teammates for UNLEASH Hacks, 2023. Throughout the hackathon Lilan was proactive, easy to work with, and always eager to help. One thing I learnt while working with him is how to keep the conversation flowing; which is only possible when a person is as curious as Lilan. Any team would be delighted to work with someone as knowledgeable as him.",
  },
  {
    date: "September 15, 2023",
    name: "Srideep Mitra",
    position: "Asia-Pacific Associate",
    relationship: "Srideep worked with Lilan but on different teams",
    image: "assets/img/recommendation/Srideep Mitra.png",
    linkedin: "https://www.linkedin.com/in/srideep-mitra-a74568170/",
    recommendation:
      "Have collaborated closely with Lilan, during multiple dialogues. I have been particularly impressed by his leadership skills and expertise in all the areas that Lilan represents. He is a collaborative team player and an innovative thinker, with a great far-sighted vision for the entire world. To conclude, Lilan is an exceptional person to work with and I look forward to collaborating with him again.",
  },
  {
    date: "September 5, 2023",
    name: "Akame Nnoko Remi Jeol",
    position: "Human Rights Connected Regional Associate for Central Africa",
    relationship: "Akame Nnoko worked with Lilan on the same team",
    image: "assets/img/recommendation/Akame Nnoko Remi Jeol.png",
    linkedin: "https://www.linkedin.com/in/akame-nnoko-remi-jeol-b284a4184/",
    recommendation:
      "I met Lilan at the COY17 in Egypt. He is a youyh enthisiast with multi-skills. He is passionate about climate action and he is into intense research in the agro sector. He commits to innovation and entrepreneurship. He possesses excellent communication and analytical skills. He is well travelled to present papers and participate in high panel discussion in international conferences across the globe. He is an indefatigable young man with the passion to institution change",
  },
  {
    date: "July 9, 2023",
    name: "Abishesh Dahal",
    position: "Solar Power Consultant",
    relationship: "Abishesh worked with Lilan on the same team",
    image: "assets/img/recommendation/Abishesh Dahal.png",
    linkedin: "https://www.linkedin.com/in/abishesh-dahal-5a495a231/",
    recommendation:
      "Lilan is a highly skilled and experienced professional with a deep understanding of biodiversity and its importance and also passionate about conservation and are committed to making a difference in the world. He has shown an excellent communicator and is able to effectively convey complex scientific concepts to a variety of audiences. It was great to work with you as you always have been a team person . I hope you will even achieve higher than this as you already have demonstrated the skills and hunger for success.",
  },
  {
    date: "June 4, 2023",
    name: "Hiruni Perera",
    position: "Co-Founder of Nico Legal",
    relationship: "Hiruni worked with Lilan on the same team",
    image: "assets/img/recommendation/Hiruni Perera.png",
    linkedin: "https://www.linkedin.com/in/-hiruni-perera/",
    recommendation:
      "I had the privilege of witnessing Lilan's journey from the early stages of his startup as the founder of Elzian Agro. As a previous participant in the Founder Institute program, I've seen him evolve into a remarkable entrepreneur. His dedication, creativity, and relentless pursuit of excellence have been truly inspiring. Lilan's ability to leverage technology to revolutionize the agricultural industry is commendable. Not only has he received numerous awards and recognition, but he has also demonstrated exceptional leadership skills. I highly recommend Lilan for his innovative vision and unwavering commitment to driving positive change in the world of entrepreneurship.",
  },
  {
    date: "May 31, 2023",
    name: "Probin Tripura",
    position: "Assistant Director - Program",
    relationship: "Probin worked with Lilan but they were at different companies",
    image: "assets/img/recommendation/Probin Tripura.png",
    linkedin: "https://www.linkedin.com/in/probintripura/",
    recommendation:
      "I had the honor of crossing paths with Lilan Dayananda during the Youth4Climate Global Summit 2022 in New York. His profound dedication to environmental sustainability through his agricultural-based startup is commendable. Notably, his exceptional capacity to mobilize communities and effect substantial change is truly remarkable. He is really doing great work. I extend my sincerest wishes for his continued success and fulfillment in all future endeavors.",
  },
  {
    date: "May 20, 2023",
    name: "Mariette W.",
    position: "Founder & CEO of Ecopia.id",
    relationship: "Mariette worked with Lilan on the same team",
    image: "assets/img/recommendation/Mariette W..png",
    linkedin: "https://www.linkedin.com/in/mariettewm/",
    recommendation:
      'From the months I have known Lilan in the Founder Institute (FI) Food Ecosystem program, he has proven to have exceptional teamwork and leadership skills, sharing his thoughts and ideas to excel in the "Green Team" during the FI accelerator program. His work and innovation in Elzian Agro are an exception, especially his mission to assist farmers in Sri Lanka. \n\n But most of all, his curiosity and take on continuous learning are exceptional. I appraise him for his endeavors in Elzian Agro!',
  },
  {
    date: "May 2, 2023",
    name: "Sayuri Kariyawasam",
    position: "Medical Doctor(MBBS)",
    relationship: "Sayuri worked with Lilan but on different teams",
    image: "assets/img/recommendation/Sayuri Kariyawasam.png",
    linkedin: "https://www.linkedin.com/in/sayuri-kariyawasam-515488248/",
    recommendation:
      "I had the opportunity to interact with Lilan during the Innovation Lab and was impressed by his professionalism, expertise, and work ethic. \n\n Lilan is an exceptional UNLEASH Talent who excels in his field of work (SDG2, SDG13 & SDG15). He has a strong knowledge base and a keen eye for detail. His ability to analyze complex biodiversity and agricultural problems and develop effective solutions is remarkable. As a fellow Global Talent, Lilan is a pleasure to work with. He is proactive and always willing to take on additional responsibilities, demonstrating a positive attitude and a willingness to help others. \n\n During the UNLEASH Innovation Lab, I saw that he worked collaboratively with other Global Talents and Mentors from various SDG Teams and fostered a supportive effort toward UNLEASH mission. He is a natural leader who can motivate and inspire others.",
  },
  {
    date: "May 1, 2023",
    name: "Panine Yassegoungbe",
    position: "Student in Management of Animal resources",
    relationship: "Panine worked with Lilan on the same team",
    image: "assets/img/recommendation/Panine Yassegoungbe.png",
    linkedin: "https://www.linkedin.com/in/panine-yassegoungbe-4b3240223/",
    recommendation:
      "I am writing to recommend Lilan Dayananda, who has been a Global Talent alongside me in UNLEASH Innovation Lab in India 2022. Throughout the Innovation Lab, I have had the pleasure of working closely with Lilan and observing his exceptional abilities and dedication to Sustainable Development Goals through UNLEASH methodology. \n\n Lilan has demonstrated a remarkable capacity for organizing skills, consistently producing high-quality work that has contributed significantly to the success of our team. His commitment stands out as particularly impressive, and I do not doubt that he will continue to excel in similar endeavors in the future. \n\n Beyond his impressive technical abilities, Lilan is an excellent collaborator, consistently exhibiting strong communication skills and an ability to work well with others. He is always willing to go the extra mile to support others, and his positive attitude and helpfulness have been invaluable during the UNLEASH Innovation Lab in India.",
  },
  {
    date: "March 16, 2023",
    name: "Pankajan Satkunam",
    position: "Technical Lead of Elzian Agro",
    relationship: "Pankajan worked with Lilan on the same team",
    image: "assets/img/recommendation/Pankajan Satkunam.png",
    linkedin: "https://www.linkedin.com/in/pankajan05/",
    recommendation:
      "I have had the pleasure of working closely with Lilan for the past several years and have been consistently impressed by his drive, vision, and leadership skills. As an entrepreneur, Lilan has a unique ability to identify market opportunities, develop innovative solutions, and execute business strategies with precision and excellence. \n\n Throughout his tenure as a founder and CEO of Elzian Agro, Lilan has demonstrated an unwavering commitment to his team and customers, always placing their needs and interests at the forefront of every decision. He is an exceptional communicator and collaborator, inspiring and motivating his colleagues to achieve their best work and reach new heights of success.",
  },
  {
    date: "March 2, 2023",
    name: "Dr Narasimha Reddy Basani",
    position: "Founder of Roligt",
    relationship: "Dr Narasimha Reddy worked with Lilan but they were at different companies",
    image: "assets/img/recommendation/Dr Narasimha Reddy Basani.png",
    linkedin: "https://www.linkedin.com/in/dr-narasimha-reddy-basani-88a974188/",
    recommendation:
      "Lilan is a young professional with serious maturity in different aspects-building teams, networking, and management. He’s been our cohort member at the Founder institute Food accelerator and I had great learnings from Lilan. His energy is contagious and the approach he has to build his startup is commendable. He is supportive and is the go-to guy for know-how in people management, and product development. \n\n His passion to build sustainable ecosystems is admirable and anyone with similar interests can take his guidance.",
  },
  {
    date: "January 24, 2023",
    name: "Anel Smagulova",
    position: "Member of Global Shapers Community",
    relationship: "Anel worked with Lilan on the same team",
    image: "assets/img/recommendation/Anel Smagulova.png",
    linkedin: "https://linkedin.com/in/anel-smagulova-b08b52156/",
    recommendation:
      "I had a pleasure to work with Lilan during the Unleash Innovation Lab in India. I was amazed by his entrepreneral talent and exeptional way of thinking that he demostrated while brainstorming processes in the Innovation lab. Other than that as a specialist in Central Asian Regional Ecological Centre I believe that the company that Lilan founded has a great potential which can help farmers and land users in CA countries.",
  },
  {
    date: "September 19, 2022",
    name: "Hani A.",
    position: "Intern of Initiatives of Land, Lives and Peace",
    relationship: "Hani worked with Lilan but on different teams",
    image: "assets/img/recommendation/Hani A..png",
    linkedin: "https://www.linkedin.com/in/hani-a-85749385/",
    recommendation:
      "When I managed to work beside Lilan in the Creative Leaders conference and when he managed to show his ambition and willpower to succeed. He was an absolute blessing to work with! I admired his creativity and his pure entrepreneur mindset of his project and I recommend anyone to work with Lilan. His brilliance and consistency has thrived him to new heights and has the capability to make those around him more competent and motivated.",
  },
  {
    date: "September 18, 2022",
    name: "Rogers Githinji",
    position: "Consultant",
    relationship: "Rogers worked with Lilan but they were at different companies",
    image: "assets/img/recommendation/Rogers Githinji.png",
    linkedin: "https://www.linkedin.com/in/rogers-githinji-690894177/",
    recommendation: "Lilan is an exceptional young leader with great interpersonal skills.",
  },
  {
    date: "August 15, 2022",
    name: "Gabriel Yohendran",
    position: "Founder of Model factory",
    relationship: "Gabriel worked with Lilan but they were at different companies",
    image: "assets/img/recommendation/Gabriel Yohendran.png",
    linkedin: "https://www.linkedin.com/in/gabriel-yohendran-2a236487/",
    recommendation:
      "When Lilan participated in our accelerator (Founder Institute - Sri Lanka) his work was exemplary. \n\n During the program Lilan proved to be very resourceful and detail oriented. Since then he has shown skill in implementing unique strategies to get outsize results. He continues to contribute to our community and is always willing to step up.",
  },
  {
    date: "June 22, 2022",
    name: "Nadit Khatri",
    position: "Founder & CEO at Pankh",
    relationship: "Nadit and Lilan studied together",
    image: "assets/img/recommendation/Nadit Khatri.png",
    linkedin: "https://www.linkedin.com/in/naditkhatri/",
    recommendation:
      "Lilan is an extremely outgoing & plain sailing person who enjoys being in constant action and believes in hard work. A person whose leadership skills are awe-inspiring and one who stands for others with extreme focus & is an excellent listener. I personally get inspired by him how he mixes Marketing with Psychology, keeps his startup lean, engages & enrolls people around him into his vision, and the application of his almost impeccable growth hacking techniques. His ability to be in constant learning, action and still be able to do multiple projects catering to each facet of it is beyond borders, something to take admiration from. His ability to think at a macro note, strategize at a micro-level and implement teamwork & action allows him to go beyond. I highly recommend Lilan as a leader who goes beyond and continue to work with him.",
  },
  {
    date: "May 15, 2022",
    name: "Arosha Dissanayake",
    position: "Executive-Cost Accounting",
    relationship: "Arosha and Lilan studied together",
    image: "assets/img/recommendation/Arosha Dissanayake.png",
    linkedin: "https://www.linkedin.com/in/arosha-dissanayake-904937209/",
    recommendation:
      "I met Lilan at the University of Kelaniya while following the Bachelor of Business Management (Special) Degree in Accountancy. Throughout academic activities, he showcased leadership by covering group assignments. He is exceptionally a good leader, has innovative ideas, has teamwork skills, and seeks opportunities to do new things. He has a way of achieving things from unorthodox methods. Moreover, he contributed his leadership skills to a lot of university extracurricular activities and societies. Furthermore, he was one of the outstanding students in our department and has solid knowledge through globally recognized professional qualifications (ACCA & CIMA). \n\n I wish him all the best in his future endeavors.",
  },
  {
    date: "May 14, 2022",
    name: "Shashinika Senanayaka",
    position: "Assistant Manager Academic Administration ",
    relationship: "Shashinika and Lilan studied together",
    image: "assets/img/recommendation/Shashinika Senanayaka.png",
    linkedin: "https://www.linkedin.com/in/shashinika-senanayaka-716a93200/",
    recommendation:
      "Lilan has high capabilities in team coordination and taking greater responsibilities. He is a great team player in the group, able to coordinate with all team members in any environment.",
  },
  {
    date: "May 13, 2022",
    name: "Nisansala wijekoon",
    position: "Senior Lecturer at the University of Kelaniya",
    relationship: "Nisansala was Lilan’s teacher",
    image: "assets/img/recommendation/Nisansala wijekoon.png",
    linkedin: "",
    recommendation:
      "Lilan who personally known for around eight years beginning from his entry as an undergraduate to follow the Bachelor of Business Management (Special) Degree in Accountancy programme conducted by the Department of Accountancy of University of Kelaniya, in Sri Lanka. In my academic engagements with Lilan as a lecturer at the Department of Accountancy, I have identified him to be confident, committed, methodical individual who can work comfortably and cooperatively with others. He has shown a keen interest and a great enthusiasm in his work and necessary skills and motivation to studies. Lilan was a highly dedicated, hardworking and organized student who worked steadfastly to meet all the deadlines for timely completion of his degree. His level of communication and working ability in English language is considered as another additional advantage. Lilan has my professional endorsement and I strongly recommend him.",
  },
  {
    date: "April 30, 2022",
    name: "Peter Bodik",
    position: "Talent Acquisition Consultant",
    relationship: "Peter worked with Lilan but on different teams",
    image: "assets/img/recommendation/Peter Bodik.png",
    linkedin: "https://www.linkedin.com/in/peter-bodik/",
    recommendation:
      "Lilan and I met as volunteers for the Berlin-based nonprofit Careers in the Common Good (CCG). He is an exceptionally bright and forward-thinking young professional with a natural ability to inspire and lead others. Driven by a strong sense of purpose and an urging desire to make an impact, he is committed to forging his own career path as a founder and entrepreneur despite all the apparent risks and caveats of the current economic crisis in his home country of Sri Lanka. I am particularly impressed by his entrepreneurial activities in the smart agronomy arena where his focus is on supporting the achievement of the second Sustainable Development Goal – Zero Hunger.",
  },
  {
    date: "March 18, 2022",
    name: "Chathura Prasad",
    position: "Quality Assurance Executive",
    relationship: "Chathura worked with Lilan on the same team",
    image: "assets/img/recommendation/Chathura Prasad.png",
    linkedin: "https://www.linkedin.com/in/chathura-prasad-2b6536149/",
    recommendation:
      "Lilan is very dedicated and talented fellow. I have met him in best speaker contest organized by his university and also at gavel conference. As an entrepreneur I wish him all the best for hos future carrier ❤️",
  },
  {
    date: "February 27, 2022",
    name: "Prarthana Saakha",
    position: "President of NYEF KathmanduNYEF Kathmandu",
    relationship: "Prarthana worked with Lilan on the same team",
    image: "assets/img/recommendation/Prarthana Saakha.png",
    linkedin: "https://www.linkedin.com/in/prarthanasaakha/",
    recommendation:
      "Lilan is a real hard worker and his dedicated is inspirational. We were in the same Cohort of FI program where he set the benchmark of being a Cohort leader. I belonged to a different country but he made sure I don't feel uncomfortable or left out, which is why I appreciate his leadership the most. Also, the passion he has for his ideas and team was demonstrated during his pitch. Thanks Lilan for being a great friend, amazing mentor and a wonderful human being!",
  },
  {
    date: "January 11, 2022",
    name: "Miikke Abaysinghe",
    position: "CEO of Runeware Audiovisual and Integrated Solutions (Pvt) Ltd.",
    relationship: "Miikke worked with Lilan but they were at different companies",
    image: "assets/img/recommendation/Miikke Abaysinghe.png",
    linkedin: "https://www.linkedin.com/in/miikkeabaysinghe/",
    recommendation:
      "I have worked with many professionals throughout my career, but Lilan was indeed a unique individual to work with. His work ethics are pristine, and he can easily adjust to any given professional situation. His ability to go out of his way to help others has made him stand out amongst his peers and he can work through any crisis and develop creative ways to achieve targets. Combined with his sense of humor and empathy he manages to uplift the spirit in stressful situations. I highly recommend working him, bon chance!",
  },
  {
    date: "December 20, 2021",
    name: "Supun Dissanayake",
    position: "Software Architect",
    relationship: "Supun worked with Lilan on the same team",
    image: "assets/img/recommendation/Supun Dissanayake.png",
    linkedin: "https://www.linkedin.com/in/supun-dissanayake-76524937/",
    recommendation:
      "I have met Lilan when I was in the Founder Institute cohort in 2021. Lilan is one of the very few inborn entrepreneurs I have met who has a great vision and knows how to execute it. He's also skilled in understanding any business and finding solutions for even the most complex problems. He is also is exceptionally skilled in finance, marketing, and operations management. In addition to that, he's a continuous learner who learns many new subjects that adds value to his business. Working with Lilan during the cohort was a great experience because of his leadership skills. He's a good collaborator, motivates his peers, and has great empathy. Because of all his skills, he has the potential to be a massively successful entrepreneur who creates value for his customers, ensures the satisfaction of his employees while being profitable in his business.",
  },
  {
    date: "December 15, 2021",
    name: "Ishara Sandaruwan",
    position: "System Administrator of Elzian Agro",
    relationship: "Ishara worked with Lilan on the same team",
    image: "assets/img/recommendation/Ishara Sandaruwan.png",
    linkedin: "https://www.linkedin.com/in/ishara-sandaruwan/",
    recommendation:
      "Lilan is one of the most hardworking individuals I've ever had the pleasure of working with. Excellent attention to detail, great management, and communication skill. He is one of the most innovative people I know and Lilan uses that to his advantage every opportunity he gets. When put in a leadership role, his intelligence and hands-on approach shine through. Always capable of adapting to a sticky situation and using that to his advantage is one of his specialties, I would say. And Lilan always managed to garner the respect of every individual he works with within a narrow time. As a dear colleague of mine, he earns my highest recommendation.",
  },
  {
    date: "December 15, 2021",
    name: "Puviraj Vinothan",
    position: "Account Manager",
    relationship: "Puviraj and Lilan studied together",
    image: "assets/img/recommendation/Puviraj Vinothan.png",
    linkedin: "https://www.linkedin.com/in/puviraj/",
    recommendation:
      "Lilan and I met at Founder Institute. He is a really talented individual who keeps all of our team members motivated at all times. Thanks a lot for your all support 🙂",
  },
  {
    date: "November 19, 2021",
    name: "Udaya Krishantha",
    position: "Founder / Director of QR Meals",
    relationship: "Udaya worked with Lilan on the same team",
    image: "assets/img/recommendation/Udaya Krishantha.png",
    linkedin: "https://www.linkedin.com/in/udaya-krishantha/",
    recommendation:
      "There are some people who are born to be entrepreneurs, they are born to bring changes in the community or even to create the community which never existed before, Lilan is one of them. \n\n I have had the pleasure of knowing him since 2020, We have worked on a few of the opportunities together, He possesses a Supernatural energy source containing tonnes of Enthusiasm and Passion and is still able to manage his down to earth character and treats everyone equally, He is a true example of humble Human, Energetic Entrepreneur, Kind mentor, and Curious Learner.",
  },
  {
    date: "October 12, 2021",
    name: "Dulanjana Hasarinda",
    position: "Senior Software Quality Assurance Engineer",
    relationship: "Dulanjana reported directly to Lilan",
    image: "assets/img/recommendation/Dulanjana Hasarinda.png",
    linkedin: "https://www.linkedin.com/in/dulanjana-hasarinda-63a33218b/",
    recommendation:
      'Lilan is a motivated, hard-working, and intelligent person who is expertise in his area. We both got to know from "Career Fair 2019" held at Kelaniya University. Lilan is a multitalented person and I gained various skills that help me in every aspect from him. He always thinks about new ideas. As the president of the Adventure club - University of Kelaniya, I saw his leadership qualities . Lilan is a good team leader .His work ethics are pristine, and he is easily adjustable to a given situation. His ability to go out of his way to help others has made him stand out. I wish all the best for your future endeavors Lilan !',
  },
  {
    date: "August 24, 2021",
    name: "Supun Jayarathne",
    position: "Software Engineer",
    relationship: "Supun and Lilan studied together",
    image: "assets/img/recommendation/Supun Jayarathne.png",
    linkedin: "https://www.linkedin.com/in/supun-jayarathne-7a6431192/",
    recommendation:
      "We have known each other since my school time and the period I was studied at the University of Kelaniya. I had the pleasure of doing a few works on some volunteer events with him and seeing how clever he is. I like his positive attitude. He is an exceptional learner and his knowledge in Marketing is very extensive. His ability of multitasking helped him to become an expert in the field that he works.",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
  {
    date: "",
    name: "",
    position: "",
    relationship: "",
    image: "assets/img/recommendation/.png",
    linkedin: "",
    recommendation: "",
  },
];
